- oauth/refresh.go
Based on an example at https://auth0.com/docs/api-auth/tutorials/adoption/refresh-tokens which shows sending the `audience` parameter during the token refresh. This allows rules in the auth system to depend on the audience when refreshing tokens.
> feat: send endpoint params for token refresh

- cli/transport.go
- cli/transport_test.go
This fixes a bug where a temporarily broken API route to get the service description could result in a 24-hour cache of the *error* and needing to clear the cache before being able to use the API again. The easy fix is to just never cache error responses when trying to refresh the API description document.
> fix: do not cache error responses

- cli/operation.go
- cli/operation_test.go
Sometimes the default value isn't specified. In that case, if the parameter is the zero value for the type, we should not send it.
> fix: do not send implied default param values, fixes #9

- cli/request.go
- cli/request_test.go
Previously we swallowed the error and something non-obvious would fail. This panics and stops execution immediately with a better error.
> fix: show error on auth hook failure

- cli/readable.go
- cli/readable_test.go
This was because we never checked for newlines when trying to optimize the single-item list case. Fixes #3.
> fix: bad indentation for short list with newlines

- cli/cli.go
In what I assume was an attempt at optimization, we never looked at the body input for generic HTTP calls (i.e. when not using high-level operation names from OpenAPI docs) **unless** arguments are also passed on the commandline. This results in weird behavior, so that check is removed. Now we always look at *both* stdin and arguments for potential input to the command.
Examples which now all work properly:
```sh
$ restish post :8000/foo
$ restish post :8000/foo <input.json
$ restish post :8888/foo id: value <input.json
```
> fix: read body from stdin for generic calls

- README.md
- cli/api.go
- cli/apiconfig.go
- cli/autoconfig.go
- cli/cli.go
- cli/interactive.go
- cli/interactive_test.go
- docs/README.md
- docs/configuration.md
- docs/openapi.md
- openapi/openapi.go
- openapi/openapi_test.go
Adds support for an **optional** `x-cli-config` OpenAPI extension to let APIs tell Restish (and other clients) how to automatically configure themselves to make authenticated requests to the API, asking for user input for just the minimum set of necessary things (like secrets). This *significantly* simplifies having customers onboard to using a tool like Restish.
> feat: Autoconfiguration via x-cli-config

- cli/autoconfig.go
- cli/interactive.go
- docs/openapi.md
Adds the ability to exclude prompt variables for CLI auto-configuration and gives a little more control over the variable naming when prompting the user.
> feat: ability to exclude autoconfig prompt vars

- cli/apiconfig.go
- cli/cli.go
- cli/flag.go
- cli/interactive.go
- cli/request.go
- docs/configuration.md
- openapi/openapi.go
- openapi/openapi_test.go
This PR adds two main changes:
This was an outstanding TODO item in the code. 
It will use all `enum` values, or the `default` value if no `enum` is given. The openapi spec mandates that either of these are set.
This adds a TLS section to the API configuration object. It allows specifying InsecureSkipVerify, an additional CA cert, and client certs.
Client certs are not added as an API authentication method, since they are often used in together with these other authentication methods.
Global CLI options have been added to overwrite the API specific options and to be able to use them during API setup. The values used during initial API setup will be written to the config.
An additional CLI wizard/asker is also provided.
In order not to overload the wizard, we do not ask for TLS parameters …
> Add support for client side TLS

- cli/cli.go
- cli/formatter.go
- go.mod
- go.sum
Allows to format response as a simple table. Useful for comparing tabular data in collection of many objects. 
Example usage:
restish sampleAPI get-node -f ..connections[].{protocol, sourceNode, connectedCount} -t
connectedCount   protocol   sourceNode 
---------------- ---------- ------------
5        tcp          abc 
2        tcp          ghi 
4        tcp          mno 
3        tcp          stu 
5        tcp          abc 
2        tcp          ghi 
4        tcp          mno 
3        tcp          stu 
5        tcp          abc 
2        tcp          ghi
> feat: Add simple table formatting support for collection of objects

- cli/api.go
- cli/request.go
This PR adds support to use environment variables in `spec_files` and profile `headers` in `~/.restish/apis.json`.
Being able to use environment variables for the `spec_files` makes it easy to share `apis.json` between team-members or workstations and being able to use environment variables for headers makes it possible to use secure environment stores (like [`envchain`](https://github.com/sorah/envchain)), minimizing the risk of credentials leaking from config files secured only by file permissions.
If you can think of more places where being able to use environment variables would be beneficial please let me know I'm happy to extend this PR.
Example `apis.json`:
```
{
"example": {
"base": "https://api.example.net",
"spec_files": ["$HOME/path/to/spec_file.yml"],
"profiles": {
"default": …
```
> feat: Expand environment variables in api spec_files and profile headers

- cli/api.go
- cli/cli.go
rsh-no-cache was not being read from the eager flags early enough, making it
impossible to invalidate the openapi spec.
This patch reads it when all the other http related eager flags are
being read.
> fix: rsh-no-cache was not being honored

- .github/workflows/ci.yaml
Also upgrades the Go version used for builds.
> chore: move off deprecated action runner

- cli/api.go
We should use the configured API profile when trying to fetch the API definition, so that any configured authentication is injected into the request.
We already do when initially probing the API endpoint.
I have also taken the liberty of removing the `WithoutLogs()` option for these requests.
Debugging why the API definition couldn't be loaded was really hard without having access to the request and response.
In general these calls are cached and won't pollute the output.
> fix: Use API profile when loading definition

- cli/api.go
Fixes a minor issue introduced with #62 where encoded responses (e.g. `br` for `Content-Encoding`) would not be decoded before trying to be processed. This is not an issue up above since `ParseResponse` also calls `DecodeResponse` inside of it.
> fix: decode after MakeRequest

- .github/workflows/ci.yaml
- .github/workflows/release.yaml
This is due to messages like:
> DEPRECATED: skipped darwin/arm64 build on Go < 1.16 for compatibility, check ...
> DEPRECATED: skipped windows/arm64 build on Go < 1.17 for compatibility, check  ...
See [example build](https://github.com/danielgtaylor/restish/runs/4530770137?check_suite_focus=true).
> fix: build/release using Go 1.17 to support arm64

- cli/param.go
Fixes a bug where `x-cli-name` for params wasn't being honored due the the code changing the param name into a dash-delimited name for command line arguments.
> fix: use param display name instead of name

- cli/formatter.go
- cli/formatter_test.go
Previously if an unknown content type was encountered then the body would be printed as hex characters. This detects displayable unicode characters (and whitespace, and BOM) and prints them as text whenever possible. This is much more user-friendly than random hex values for things that may just be JSON or YAML or text with an incorrect or missing content type.
> feat: print displayable unicode body when possible

- cli/input.go
- cli/input_test.go
Turns out sending stuff like binary files was broken because we were trying to parse them. This fixes it by making the logic:
1. If no shorthand args are passed, and we are not a tty, then read and use stdin as the request body
2. Else, process the shorthand input
> fix: sending non-structured-object input via stdin, fixes #81

- cli/operation.go
- cli/operation_test.go
- openapi/openapi.go
This fixes a bug where a param using `anyOf` with no type itself could cause a crash. Now there is no more crash and the param is treated as a plain string. Proper `anyOf` support may come some time in the future.
> fix: better handling of params with unknown types, fixes #63

- openapi/openapi.go
This prevents a bug where the URLs get generated incorrectly due to trailing slashes in the OpenAPI defined servers list. Fixes #60.
> fix: trim trailing slashes from OpenAPI servers

- cli/formatter.go
- cli/formatter_test.go
- docs/output.md
This documents how to save responses and enables the use of raw mode (`-r`) with binary files so they can be easily saved via output redirection to a file. Fixes #37.
> feat: enabled & document raw mode for saving files

- cli/param.go
- cli/param_test.go
There was a bug looping over the array of values. This fixes it and adds tests for each supported type to prevent regressions in the future!
> fix: parameter serialization for style: form, fixes #47

- cli/apiconfig.go
- cli/cli_test.go
This command forces a refresh of the named API, so users can use it to get the latest after an API release is made. Just a convenience for doing something like `RSH_NO_CACHE=1 restish your-api --help` or something along those lines to force a fetch/parse of the OpenAPI.
> feat: add api sync command

- cli/operation.go
- cli/operation_test.go
- cli/param.go
This addresses an issue brought up in #48, where it is difficult to send the default value for an argument (query/header param). Instead of comparing to the defined default or zero value, the code now considers whether an argument was passed on the command line or not and should allow sending of default values when explicitly passed to the command.
> fix: simplify option handling, send explicitly passed defaults

- README.md
- docs/README.md
- docs/openapi.md
Adds additional documentation and tries to explain how OpenAPI maps into the CLI for dynamic generation of commands, options, args, help, etc.
> docs: add anatomy of an openapi-powered cli command info

- README.md
- docs/_sidebar.md
- docs/comparison.md
- docs/index.html
- docs/input.md
Adds some extra documentation and a comparison to cURL and HTTPie. Fixes #97.
> docs: add comparison page

- cli/content.go
Some servers will respond with `text/yaml` instead of the other types. This makes sure we can detect and handle it correctly.
> fix: detect text/yaml response content type

- main.go
This makes it so that if you `go install` you will know approximately when the build is from, letting you see which version it likely was based on the releases. It's very basic and just uses the executable modification time, but is better than what we have today.
> fix: add basic build time to dev --version

- cli/formatter.go
- cli/formatter_test.go
Fixes #99. If it's a large number, and is an integer, then force a non-scientific notation representation. This mostly affects JSON as it uses `float64` for all numbers.
> fix: do not use scientific notation for large integers

- cli/formatter.go
- cli/formatter_test.go
Fixes a bug where a response may have an image content type but zero byte body, which resulted in a crash due to:
> `ERROR: Caught error: interface conversion: interface {} is nil, not []uint8`
Now it will just skip trying to write out an image if the body is `nil`.
> fix: do not panic on empty image

- cli/formatter.go
- cli/formatter_test.go
Prevents escaping `<`, `>`, and `&` in the JSON (which exists to support some legacy browsers). See also https://stackoverflow.com/a/28596225/164268
> fix: prevent escaping JSON for browsers

- cli/links.go
- cli/links_test.go
This makes sure that arrays of objects (e.g. list operations) can have parsed links as well.
> fix: find HAL links in array responses

- docs/configuration.md
- Harmonize sentence structure of the list of configuration approaches (no verb at the start)
- Split the code block into three blocks, to help drive the point home that they aren't meant as a sequence of commands
- Edit the comments in the example commands to be a bit more explicit
> docs/configuration.md: Clarify equivalent commands

- cli/lexer.go
- cli/readable.go
- cli/readable_test.go
Fixes a formatting bug where `.` was matching too many chars instead of a literal `.` and simplifies the human-readable representation of dates where the time component is empty.
> fix: formatting, simplify dates

- cli/formatter.go
- cli/formatter_test.go
- cli/request.go
This PR:
- Fixes behavior when `-f` is blank and `-r` is passed as this should just dump the raw response instead of parsing.
- Fixes base64 behavior which was broken by converting `[]byte` into `[]interface{}` which disabled the built-in base64 behavior. This is now re-enabled and also supported for raw mode.
> fix: base64 handling of []byte and raw mode on structured input

- docs/README.md
- docs/comparison.md
- docs/configuration.md
- docs/guide.md
- docs/hypermedia.md
- docs/index.html
- docs/input.md
- docs/output.md
- docs/shorthand.md
This updates the guide in various ways:
- Switch to https://api.rest.sh/ as the example URL
- Clarifications  & fixes on several pages
- Fixes to syntax highlighting
> docs: update guide & other docs

- docs/configuration.md
- docs/hypermedia.md
- docs/output.md
- docs/shorthand.md
Fixes a few missed references to api.rest.sh that will return real data.
> docs: update missed example.com reference

- cli/auth.go
The goal of this commit is to get the password used for Basic Auth from the prompt when it is not defined in the apis.json file for security reason.
> Password prompt when user defined but not password

- cli/apiconfig.go
- docs/configuration.md
This PR is to add "restish api show <name>" command.
Also adds missing "restish api sync" documentation.
Partially answering to #53
> api: add show and add missing sync documentation

- .github/workflows/ci.yaml
- cli/auth.go
Fixes a broken build on Windows due to differences in the `syscall` package. See https://github.com/danielgtaylor/restish/runs/6252893595?check_suite_focus=true.
> fix: build on windows

- openapi/example.go
When JSON schema types reference each other, the example generation code blows up the stack. This patch adds a simple mechanism to avoid going more than (a completely arbitrarily chosen value of) 5 layers deep[1].
This patch correctly fixes the panic I was previously experiencing
[1]: it felt like anything more than 5 would make reading the example complex anyhow.
> openapi: do not overflow the stack for circular types

- cli/request.go
Hello,
I'm trying to use Restish with a corporate API that requires OAuth 2.0 Client Credentials authentication.
The authentication /token endpoint also requires a client certificate.
With the current version of Restish, I've the following error message:
```
ERROR: Caught error: oauth2: cannot fetch token: 400 Bad Request
Response: <html>
<head><title>400 No required SSL certificate was sent</title></head>
...
</html>
```
With this proposed patch, it is working fine.
Can you please have a look and tell me if it can be merged?
Thanks and Regards
> Add TLS Config before Auth

- go.mod
- go.sum
Specifically this fixes broken schema syntax highlighting, which was fixed in https://github.com/charmbracelet/glamour/pull/189 and is due to the indirect dependency upgrading to https://github.com/muesli/termenv/releases/tag/v0.13.0.
> fix: upgrade glamour to get highlighter fix

- main.go
This works better than `os.Args[0]` in some cases, e.g. when the command is aliased in some shells.
> fix: get dev version via os.Executable

- cli/operation.go
- openapi/openapi.go
This feature marks operations that are deprecated in OpenAPI as deprecated in the CLI as well, effectively hiding them from the top level `--help` listing and putting a warning when using them directly by utilizing a built-in cobra feature.
> feat: mark & hide deprecated operations

- cli/apiconfig.go
- cli/cli.go
- cli/interactive.go
- cli/request.go
For APIs deployed for several environments (development, staging, production), it can be useful to share most of the configuration but to allow configuration of the URL base.
> allow overriding base url in profiles

- cli/edit.go
- cli/formatter.go
- cli/input.go
- cli/lexer.go
- cli/request.go
- docs/comparison.md
- docs/guide.md
- docs/index.html
- docs/input.md
- docs/output.md
- docs/shorthand.md
- docs/shorthandv1.md
- go.mod
- go.sum
- openapi/openapi.go
Switch to the new Shorthand v2 syntax, see https://github.com/danielgtaylor/shorthand/releases/tag/v2.0.0-beta
This replaces the Shorthand v1 CLI input as well as JMESPath for filtering as Shorthand v2 includes a query syntax to support certain patch operations.
> feat!: switch to shorthand v2

- cli/auth.go
- cli/cli.go
Some OpenAPI backed APIs implement a custom API signature scheme to provide stronger guarantees against replay attacks than those provided by OAuth.
Generally speaking, these APIs tend to either wire a computed signature in an HTTP header or in a query argument in the URL.
This patch implements a new `external-tool` auth method which executes a configured program against a JSON representation of the request built by restish. If the program returns any output it is deserialized from JSON, allowing for new headers to be set, or for the URL to be modified. This then allows small script to be used alongside restish to implement any sort of API signature mechanism.
> auth: support deferring authentication to a third party script

- cli/apiconfig.go
- cli/apiconfig_test.go
- cli/auth.go
- cli/cli.go
- cli/cli_test.go
- cli/content.go
- cli/content_test.go
- cli/edit.go
- cli/formatter.go
- cli/formatter_test.go
- cli/lexer.go
- cli/logger.go
- cli/operation_test.go
- docs/guide.md
- docs/output.md
This includes a number of small but related changes, the biggest being the breaking change in default output behavior when redirecting output to a file or pipe as it now just sends the response body as JSON when no filters are passed. List of all changes:
- Default redirected output to response body as JSON
- Remove `--rsh-table` in favor of `-o table`
- Reuse registered content types as output marshallers
- Add a `PrettyMarshaller` which content types can (optionally) provide, e.g. JSON and Ion provide one now.
- Readable output now colorizes matching braces/brackets
- Differentiate between TTY and color within the code
- When the filter `-f` option doesn't start with e.g. `body`, `headers`, or one of the valid other values it now returns an error rather than no output.
Note: this is a …
> feat!: revamp default output behavior

- openapi/openapi.go
Usage of url ResolveReference with '/openapi.json' argument prevented discovery of APIs with versions in URL, such as 'https://api.example.com/v2', only looking for 'https://api.example.com/openapi.json' instead of 'https://api.example.com/v2/openapi.json'
> fix: fix loader hints overriding the whole base url

- go.mod
- go.sum
- oauth/authcode.go
- oauth/clientcreds.go
- oauth/refresh.go
- oauth/request.go
- openapi/openapi.go
- openapi/openapi_test.go
The main change in this PR is to stop panicking when an API has circular references.
After the change I made here https://github.com/pb33f/libopenapi/pull/39 libopenapi will return both the `Model` and a list of errors, if the only errors it encountered are circular references.
Restish has no issues with processing API documents that contain circular references (verified experimentally).
An alternative implementation is to check if the Model is not nil, but I think the current implementation represents the intent better, at the expense of slightly more verbose error checking code.
I also took the liberty of fixing some deprecated function lint warnings.
Finally, I also changed the `Token` method of `RefreshTokenSource` to be a pointer receiver. The last line in that function tries to save …
> Allow circular references

- cli/api.go
- cli/cli.go
- cli/transport.go
This allows users to specify the location of the configuration and cache directory via the `RESTISH_CONFIG_DIR` and `RESTISH_CACHE_DIR` environment variables. As an example, this aids in a use case where we want to ship different API configurations for different products, let them manage the configuration, and invoke restish as needed.
If not specified, the existing default paths are used.
> Allow specifying config and cache directory via environment variables

- cli/formatter.go
This fixes a small bug introduced in the default output behavior refactor related to printing responses which have no body (e.g. HTTP 204). With this fix the behavior is back to displaying the HTTP status code and headers for such responses.
> fix: print responses without a body

- docs/README.md
Start with the why, then the how, then move in to the sales jargon
> docs: reorder sections to start with the why

- cli/cli.go
This PR makes it so you can use e.g. `restish GET api.rest.sh/example` instead of having to use lowercase verbs.
> feat: allow uppercase HTTP verbs as commands

- cli/cli.go
Small fix for a potential crash when running e.g. `restish get --help`.
> fix: crash with certain --help commands

- bulk/commands.go
- bulk/commands_test.go
- docs/bulk.md
This updates the `restish bulk list` operation to support shorthand query filters to display information from each matched file that is listed. This enables quickly looking up information across all resources, similar to how you could pass each filename to a tool like `jq` to query and print out some information for each file. The advantage here is that it is built-in using the same language as the rest of Restish.
> feat: bulk list supports shorthand query filters

- cli/cli.go
This fixes the behavior for URI templates with multiple variables, which were matching incorrectly due to breaking out of the loop. If the match is successful here we force the continue to keep going to check for other variables.
> fix: completion for multi-variable templates

- cli/cli.go
- cli/cli_test.go
- cli/flag.go
Previously commas would break the headers, e.g. sending a `Date` or `Last-Modified` or `If-Unmodified-Since` header. That was because the flags parser was splitting on commas, which is now disabled with this fix. The custom logic splitting on commas on environment variables is left in for now to support multiple headers set via the environment.
> fix: properly support commas in headers

- cli/apiconfig.go
- cli/cli.go
When an API base matches another API's base the API is chosen based on the order the JSON parser unmarshalled the apis.json.
> Fix bug #128

- .github/workflows/ci.yaml
This should ensure that the tests get run on pull requests by outside contributors as those don't trigger a `push` event.
> fix: run tests on pulls

- cli/cli.go
Related to #125, this bug prevented the error from getting returned which meant no non-zero exit code was ever set for panics. Now every panic should result in an exit code of 1.
I'm leaving the linked issue open because of the feature request for an option to exit non-zero for 3xx/4xx/5xx status codes for easier scripting.
> fix: properly set error on panic recovery

- cli/cli.go
- cli/cli_test.go
- cli/request.go
- cli/request_test.go
- docs/output.md
- main.go
This sets the exit status code depending on the HTTP response status code using 3, 4, or 5 for 3xx, 4xx, 5xx errors respectively. This is similar to HTTPie's `--check-status` and curl's `--fail-with-body`:
- https://httpie.io/docs/cli/scripting
- https://daniel.haxx.se/blog/2021/02/11/curl-fail-with-body/
Unlike those (but like [xh#144](https://github.com/ducaale/xh/issues/144)) setting the exit code is the default behavior. You can opt-out via `--rsh-ignore-status-code`.
> feat: set exit code from status code, fixes #125

- openapi/openapi.go
- openapi/testdata/petstore/openapi.yaml
This makes sure any path params are combined with operation params (op params having precedence) and modifies a test to make sure refs to params work correctly similar to the example in and fixes #152.
> fix: add test for combined path+op params and ref

- cli/cli.go
fixes 
panic: could not detect API type: ${URL}
When the help command is used on a non default profile.
> fixes 'findApi' when the help command is used

- LICENSE.md
- README.md
- docs/.markdownlint.yaml
- docs/README.md
- docs/bulk.md
- docs/comparison.md
- docs/configuration.md
- docs/guide.md
- docs/hypermedia.md
- docs/input.md
- docs/openapi.md
- docs/output.md
- docs/shorthand.md
- docs/shorthandv1.md
- Add title to license file
- Add .markdownlint.yaml file and fix several violations
- Normalize section heading capitalization to Sentence case
- Consistently spell out 'parameters'
- Various small tweaks
Inspired by #159 :)
> Various documentation fixes

- bulk/metadata.go
This fixes a bug that would sometimes leave dead meta entries and state inconsistency between local & remote, telling you there are diffs and the need to pull when that wasn't the case, particularly for deleted files.
> fix: bulk version inconsistency bug

- openapi/openapi.go
- openapi/testdata/request/openapi.yaml
- openapi/testdata/request/output.yaml
Fixes #174, #158. The logic is similar to #174 but explicitly uses the base path through the updated resolver interface.
> fix: use configured base as base path if no servers present

- bulk/commands.go
- docs/README.md
- docs/bulk.md
- docs/comparison.md
- docs/guide.md
- docs/input.md
- docs/shorthandv1.md
Following-up from #160, I've edited the docs so they demonstrate usage of the capitalized forms of the HTTP verbs.
I think given the prevalence of that representation, it's acceptable (and desirable, even) to default to that form in the docs. Let me know if you think otherwise, though :)
> docs: use capitalized forms of HTTP verbs

- go.mod
- go.sum
Fixes a bug where queries like this would break: `foo.{bar: {baz: another}}`
> fix: upgrade shorthand to fix nested field selection bug

- .github/workflows/ci.yaml
- cli/interactive.go
- cli/interactive_test.go
"Setup", as a single word, represents a noun (i.e. a configuration). The verb usage requires splitting the two words: "set up".
> Correct occurrences of "Setup" that should say "Set up" instead

- docs/configuration.md
- Link to the sections for each authentication type
- Clarify section about editing an existing configuration
- Fix typo: "persistend" → "persistent"
> docs: Improve API configuration documentation

- docs/guide.md
It's better to be explicit about where the information is located, than to vaguely suggest "reading on" :)
> docs: link directly to section on registering APIs

- README.md
- The comparison with curl/httpie is not part of the user guide; moved it to the first paragraph
- Explicitly mention that the user guide describes both installation and usage
> Clarify docs links in README

- cli/content.go
- cli/gron.go
- cli/gron_test.go
also updated the test to show it's handling the pesky `<`, `>`, `&` chars.
> finished last bit of the gron outputter implementation

- docs/guide.md
Restish has been added to the Nixpkgs directory with <https://github.com/NixOS/nixpkgs/pull/243465> (Thanks @fabaff!) , so now there's an additional method to install it.
This PR expands the installation instructions and includes a mention of Nixpkgs as another way to install Restish.
By the way, we might want to link to [Repology](https://repology.org/project/restish/versions) for even more installation methods (e.g. there's AUR for ArchLinuz, MacPorts for macOS, pkgsrc for netbsd, Scoop for Windows, and even Termux for Android.
> Expand installation instructions; add Nixpkgs option

- cli/apiconfig.go
- cli/apiconfig_test.go
- docs/schemas/apis.json
- docs/shorthand.md
Add a basic `restish api edit` command to edit the API config file now that it's in different locations depending on the operating system.
Also adds a schema for the `apis.json` config file, making it easier to edit in VSCode and other editors.
> feat: API edit command; apis.json schema

- cli/api.go
- cli/apiconfig.go
- docs/configuration.md
- docs/schemas/apis.json
This adds a new config option to override the operation base path when the API base path has a path component.
Also included are some improvements to the config JSON schema to make editing easier with suggested auth params and auth schema name values.
> feat: operations base path config option

- openapi/openapi.go
- openapi/testdata/extensions/output.yaml
- openapi/testdata/long_example/output.yaml
- openapi/testdata/petstore/output.yaml
- openapi/testdata/request/output.yaml
Since the built-in `--help` generator only gives a name of each argument and a short text description of each option, this PR adds schema information for both to the generated description. There are two groups: 1. path parameter arguments and 2. query param / header arguments. Each is rendered as an object where the keys are the parameter name and the schema for each is shown next to it, similar to how the request/response body schemas work.
To take the example in #157, it now produces this to describe the image type argument:
> feat: document args/options schemas, fixes #157

- openapi/openapi.go
- openapi/testdata/request/openapi.yaml
- openapi/testdata/request/output.yaml
If an OpenAPI operation has no operation ID, then generate it using the method+path, converted to kebab casing. For example, `GET /users/{user-id}/friends` → `get-users-user-id-friends`. No attempt is made to infer what arguments might mean or whether something is a list vs get.
> fix: generate operation ID if not present, fixes #201

- cli/api.go
- cli/api_test.go
- cli/testdata/petstore.json
- go.mod
- go.sum
- openapi/openapi.go
- openapi/openapi_test.go
- openapi/schema.go
This supercedes #202. It has the following changes built on top of it:
1. Merge in the latest from `main`
2. Set the base URL or path to allow resolving relative references. This was required to get e.g. the DigitalOcean API working.
3. Fix printing of min/max/etc now that they are floats using `%g`. I ran into an example where a max of `0.1` incorrectly rendered as `0` and using just `%f` has too many default digits for human readability.
Tested with various public and private APIs, including:
```json
{
"do": {
"base": "https://api.digitalocean.com/v2",
"profiles": {
"default": {
"headers": {
"authorization": "** REMOVED **"
}
}
},
"spec_files": [
"https://raw.githubusercontent.com/digitalocean/openapi/main/specification/DigitalOcean-public.v2.yaml"
]
},
"github": {
"base": …
```
> Support remote references in openapi

- .github/workflows/release.yaml
- .goreleaser.yml
- README.md
- cli/cli.go
- cli/cli_test.go
- cli/flag.go
- cli/request.go
- cli/request_test.go
- docs/README.md
- docs/_sidebar.md
- docs/index.html
- docs/retries.md
This adds support to Restish for automatic retries and timeouts. See the updated docs for examples. Here is what it looks like in practice:
```sh
$ restish api.rest.sh/status/429?x-retry-in=200ms
WARN: Got 429 Too Many Requests, retrying in 200ms
WARN: Got 429 Too Many Requests, retrying in 200ms
HTTP/2.0 429 Too Many Requests
... response headers truncated ...
```
This updates the core request handling functionality in Restish, so it equally applies to bulk resource management and any scripts you may have with loops or pagination making many requests over a short period of time.
Also includes some minor updates to the release scripts and the frontend syntax highlighter to make the examples pretty.
> feat: retries & timeouts

- cli/content.go
- cli/gron.go
- cli/gron_test.go
This simplifies the `PathBuffer` (and makes it a bit more inefficient) to generally lower complexity and ensure the correct output for fields containing `.`, `]`, or `"` characters in their name.
Fixes #217
> fix: gron output with special chars

- docs/shorthand.md
`go get -u github.com/danielgtaylor/shorthand/cmd/j` did not work for me. I ran it from a golang docker container because I do not have any go development environment available. Following error messages from the `go` command, I ended up with `go install github.com/danielgtaylor/shorthand/cmd/j@latest` which worked and installed the `j` executable in `/go/bin/j`.
> Update docs to use `go install` instead of `go get`

- cli/api.go
- cli/request.go
Also ignores any CLI or env parameters passed in when querying for API definitions: only profile specified params are used.
I also took the liberty of refactoring how the options work.
Final note: the tests timeout when ran natively on mac silicon (at least on my machine). They pass in a ubuntu VM.
Fixes #216
> fix(api): Do not cache server responses when refreshing API defs

- cli/interactive.go
This replaces the input for passwords/secrets with `*` using the existing `survey` library. It looks like it was recently archived, so we'll need to replace it at some point.
> fix: hide secret input during API config, fixes #232

- cli/apiconfig.go
- cli/apiconfig_test.go
This adds a basic profile-aware command to clear the auth token cache, so you don't have to try and find the `cache.json` file, find the right line, and delete it in order to force e.g. OAuth2 re-auth. Now it's a simple:
```sh
$ restish api clear-auth-cache $NAME`
```
Pass `--rsh-profile=$PROFILE` or `-p $PROFILE` to clear the cache for a specific profile instead of `default`.
> feat: add command to clear auth token cache

- docs/bulk.md
- docs/guide.md
- docs/openapi.md
This PR fixes several links in the docs. Some of them didn't quite get you to the right section of the page, or they added some unnecessary characters to the URL.
None of these links were broken, but their navigation wasn't spot-on, which might have caused some confusion. Also, a few links had an extra `./` after the URL's fragment identifier but before the page identifier (e.g. `rest.sh/#/./shorthand?id=querying`).
> docs: improve link accuracy

- .github/workflows/ci.yaml
- cli/apiconfig.go
- cli/request.go
- docs/schemas/apis.json
- go.mod
- go.sum
This has been tested with a Yubikey and the OpenSC PKCS#11 interface on Linux.
> Make it possible to use a client certificate stored in hardware

- oauth/authcode.go
- oauth/authcode_test.go
Fixes #248.
PR escapes '&' character to enable oAuth flow for Windows operating systems.
Aside of the test @DominicBortmes as able to verify the fix for his context.
> Escape '&' for Windows command line oAuth flow

- cli/apiconfig.go
- cli/apiconfig_test.go
Currently, regardless of the `COLOR` / `NOCOLOR` environment settings, the output of `restish api show $API` is output in color. This is quite inconvenient when piping the output to other programs which are unable to process the ANSI color codes. In my case, this specifically breaks piping the output into `jq`.
For example, with the current release:
```console
$ restish api show default | jq '.profiles.default.headers | keys[]'
jq: parse error: Invalid numeric literal at line 1, column 2
```
With this fix included:
```console
$ restish api show mc | jq '.profiles.default.headers | keys[]'
"authorization"
```
> Do not output colorized config when environment does not support it

- .github/workflows/ci.yaml
- .github/workflows/release.yaml
- bulk/commands.go
- go.mod
- go.sum
Upgrades to Go 1.24 and hopefully lets us keep up to date with any dependabot updates (as well as using the latest language features).
> feat: upgrade to Go 1.24

- oauth/authcode.go
- oauth/refresh.go
This small PR sends the scopes originally requested when fetching an access token to the refresh token endpoint (if one is available). I ran into an issue where Azure Entra refuses the refresh token unless the scopes match the original request. I *believe* this is safe to do as the spec labels this field as optional and other auth systems should either confirm the scopes are equal or ignore it, but could use some help testing.
BTW, the auth package is missing a lot of tests, so I haven't added one here, but eventually it would be nice to get some tests there.
> fix: send scopes on refresh token requests
